/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/email-verification/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify user email address
         * @description Verifies a user's email address using the token sent via email during registration.
         *     Once verified, the user can access endpoints that require verified status.
         */
        get: operations["verify_user_email_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticates a user with email and password, returns JWT access and refresh tokens.
         */
        post: operations["login_user_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User logout
         * @description Revokes the provided refresh token, preventing it from being used to generate new access tokens.
         *     Even if token revocation fails internally, the client is informed of successful logout for better UX.
         */
        post: operations["logout_user_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Exchanges a valid refresh token for a new access token and refresh token pair.
         *     The old refresh token is revoked and cannot be reused.
         */
        post: operations["refresh_token_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account and sends a verification email.
         *     The user must verify their email before they can access protected endpoints.
         */
        post: operations["register_user_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user's CVs
         * @description Retrieves a paginated list of CVs owned by the authenticated user.
         *     Supports search filtering and sorting by creation/update date.
         */
        get: operations["get_cvs_handler"];
        put?: never;
        post: operations["create_cv_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Returns the profile information for the authenticated user.
         *     Requires a valid JWT access token.
         */
        get: operations["get_user_profile_handler"];
        /**
         * Update current user profile
         * @description Updates the authenticated user's profile information. Currently only full name can be updated.
         */
        put: operations["update_user_profile_handler"];
        post?: never;
        /**
         * Delete current user account
         * @description Soft deletes the authenticated user's account. The account is marked as deleted
         *     but data is retained in the database. This action requires authentication.
         */
        delete: operations["soft_delete_user_handler"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CVInfo: {
            /**
             * @description Biography
             * @example Passionate software engineer...
             */
            bio: string;
            /** @description Contact information */
            contact_info: components["schemas"]["ContactDetail"][];
            /** @description Core skills */
            core_skills: components["schemas"]["CoreSkill"][];
            /**
             * @description Display name
             * @example John Doe
             */
            display_name: string;
            /** @description Educational background */
            educations: components["schemas"]["Education"][];
            /** @description Work experiences */
            experiences: components["schemas"]["Experience"][];
            /** @description Highlighted projects */
            highlighted_projects: components["schemas"]["HighlightedProject"][];
            /**
             * Format: uuid
             * @description CV unique identifier
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Profile photo URL
             * @example https://example.com/photos/profile.jpg
             */
            photo_url: string;
            /**
             * @description Professional role
             * @example Senior Software Engineer
             */
            role: string;
            /**
             * Format: uuid
             * @description Owner user ID
             * @example 987e6543-e21b-12d3-a456-426614174000
             */
            user_id: string;
        };
        CVPageResult_CVInfo: {
            /** @description List of items in the current page */
            items: {
                /**
                 * @description Biography
                 * @example Passionate software engineer...
                 */
                bio: string;
                /** @description Contact information */
                contact_info: components["schemas"]["ContactDetail"][];
                /** @description Core skills */
                core_skills: components["schemas"]["CoreSkill"][];
                /**
                 * @description Display name
                 * @example John Doe
                 */
                display_name: string;
                /** @description Educational background */
                educations: components["schemas"]["Education"][];
                /** @description Work experiences */
                experiences: components["schemas"]["Experience"][];
                /** @description Highlighted projects */
                highlighted_projects: components["schemas"]["HighlightedProject"][];
                /**
                 * Format: uuid
                 * @description CV unique identifier
                 * @example 123e4567-e89b-12d3-a456-426614174000
                 */
                id: string;
                /**
                 * @description Profile photo URL
                 * @example https://example.com/photos/profile.jpg
                 */
                photo_url: string;
                /**
                 * @description Professional role
                 * @example Senior Software Engineer
                 */
                role: string;
                /**
                 * Format: uuid
                 * @description Owner user ID
                 * @example 987e6543-e21b-12d3-a456-426614174000
                 */
                user_id: string;
            }[];
            /**
             * Format: int32
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * Format: int32
             * @description Number of items per page
             * @example 10
             */
            per_page: number;
            /**
             * Format: int64
             * @description Total number of items across all pages
             * @example 42
             */
            total: number;
        };
        /** @enum {string} */
        CVSort: "newest" | "oldest" | "updatednewest" | "updatedoldest";
        ContactDetail: {
            /** @description Type of contact */
            contact_type: components["schemas"]["ContactType"];
            /**
             * @description Contact value
             * @example john@example.com
             */
            content: string;
            /**
             * @description Contact title/label
             * @example Work Email
             */
            title: string;
        };
        /** @enum {string} */
        ContactType: "PhoneNumber" | "WebPage";
        CoreSkill: {
            /**
             * @description Skill description
             * @example Expert in Rust, Python, and Node.js
             */
            description: string;
            /**
             * @description Skill title/name
             * @example Backend Development
             */
            title: string;
        };
        CreateCVRequest: {
            /**
             * @description Professional biography
             * @example Passionate software engineer with 10+ years of experience...
             */
            bio: string;
            /** @description Contact information */
            contact_info: components["schemas"]["ContactDetail"][];
            /** @description List of core skills */
            core_skills: components["schemas"]["CoreSkill"][];
            /**
             * @description Display name for the CV
             * @example John Doe
             */
            display_name: string;
            /** @description Educational background */
            educations: components["schemas"]["EducationRequest"][];
            /** @description Work experience */
            experiences: components["schemas"]["ExperienceRequest"][];
            /** @description Highlighted projects */
            highlighted_projects: components["schemas"]["HighlightedProjectRequest"][];
            /**
             * @description URL to profile photo
             * @example https://example.com/photos/profile.jpg
             */
            photo_url: string;
            /**
             * @description Professional role or job title
             * @example Senior Software Engineer
             */
            role: string;
        };
        /** @description Request body for user registration */
        CreateUserRequest: {
            /**
             * @description Email address
             * @example john@example.com
             */
            email: string;
            /**
             * @description Full name of the user
             * @example John Doe
             */
            full_name: string;
            /**
             * @description Password (minimum 8 characters)
             * @example SecurePass123!
             */
            password: string;
            /**
             * @description Username (unique identifier)
             * @example johndoe
             */
            username: string;
        };
        Education: {
            /** @example Bachelor of Science in Computer Science */
            degree: string;
            /**
             * Format: int32
             * @example 2015
             */
            graduation_year: number;
            /** @example MIT */
            institution: string;
        };
        EducationRequest: {
            /**
             * @description Degree obtained
             * @example Bachelor of Science in Computer Science
             */
            degree: string;
            /**
             * Format: int32
             * @description Year of graduation
             * @example 2015
             */
            graduation_year: number;
            /**
             * @description Educational institution
             * @example MIT
             */
            institution: string;
        };
        ErrorDetail: {
            /**
             * @description Error code for programmatic handling
             * @example INVALID_FILE_NAME
             */
            code: string;
            /**
             * @description Human-readable error message
             * @example Invalid file name
             */
            message: string;
        };
        /** @description Standard error response wrapper */
        ErrorResponse: {
            /** @description Error details */
            error: components["schemas"]["ErrorDetail"];
            /**
             * @description Always false for error responses
             * @example false
             */
            success: boolean;
        };
        Experience: {
            achievements: string[];
            /** @example Tech Corp */
            company: string;
            /** @example Led backend development team... */
            description: string;
            /** @example 2023-12 */
            end_date?: string | null;
            /** @example San Francisco, CA */
            location: string;
            /** @example Senior Backend Engineer */
            position: string;
            /** @example 2020-01 */
            start_date: string;
            tasks: string[];
        };
        ExperienceRequest: {
            /**
             * @description Notable achievements
             * @example [
             *       "Reduced latency by 40%",
             *       "Increased test coverage to 90%"
             *     ]
             */
            achievements: string[];
            /**
             * @description Company name
             * @example Tech Corp
             */
            company: string;
            /**
             * @description Job description
             * @example Led backend development team...
             */
            description: string;
            /**
             * @description End date (None if current position)
             * @example 2023-12
             */
            end_date?: string | null;
            /**
             * @description Work location
             * @example San Francisco, CA
             */
            location: string;
            /**
             * @description Job position/title
             * @example Senior Backend Engineer
             */
            position: string;
            /**
             * @description Start date (ISO format or readable string)
             * @example 2020-01
             */
            start_date: string;
            /**
             * @description Key tasks and responsibilities
             * @example [
             *       "Designed microservices architecture",
             *       "Mentored junior developers"
             *     ]
             */
            tasks: string[];
        };
        HighlightedProject: {
            /** @example proj-123 */
            id: string;
            /** @example A scalable e-commerce platform... */
            short_description: string;
            /** @example ecommerce-platform */
            slug: string;
            /** @example E-commerce Platform */
            title: string;
        };
        HighlightedProjectRequest: {
            /**
             * @description Project ID
             * @example proj-123
             */
            id: string;
            /**
             * @description Short project description
             * @example A scalable e-commerce platform built with microservices
             */
            short_description: string;
            /**
             * @description URL-friendly slug
             * @example ecommerce-platform
             */
            slug: string;
            /**
             * @description Project title
             * @example E-commerce Platform
             */
            title: string;
        };
        /** @description Login request from client */
        LoginRequestDto: {
            /**
             * @description Email address
             * @example john@example.com
             */
            email: string;
            /**
             * @description Password
             * @example SecurePass123!
             */
            password: string;
        };
        LoginResponse: {
            /**
             * @description JWT access token (short-lived)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token: string;
            /**
             * @description JWT refresh token (long-lived)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refresh_token: string;
            /** @description Authenticated user information */
            user: components["schemas"]["LoginUserInfo"];
        };
        LoginUserInfo: {
            /**
             * @description Email address
             * @example john@example.com
             */
            email: string;
            /**
             * @description User ID (UUID)
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Whether the user has verified their email
             * @example true
             */
            is_verified: boolean;
            /**
             * @description Username
             * @example johndoe
             */
            username: string;
        };
        /** @description Logout request from client */
        LogoutRequestDto: {
            /**
             * @description Refresh token to revoke (optional)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refresh_token?: string | null;
        };
        LogoutResponseBody: {
            /**
             * @description Success message
             * @example Logged out successfully
             */
            message: string;
        };
        RefreshTokenRequestDto: {
            /**
             * @description Refresh token to exchange for new tokens
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refresh_token: string;
        };
        RefreshTokenResponseBody: {
            /**
             * @description New JWT access token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token: string;
            /**
             * @description New JWT refresh token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refresh_token: string;
        };
        RegisterUserResponse: {
            /**
             * @description Success message
             * @example User created successfully. Please check your email to verify your account.
             */
            message: string;
            /** @description Created user details */
            user: components["schemas"]["RegisteredUser"];
        };
        RegisteredUser: {
            /**
             * @description Email address
             * @example john@example.com
             */
            email: string;
            /**
             * @description Full name
             * @example John Doe
             */
            full_name: string;
            /**
             * @description User ID (UUID)
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Username
             * @example johndoe
             */
            username: string;
        };
        /** @description Standard success response wrapper */
        SuccessResponse_RegisterUserResponse: {
            data: {
                /**
                 * @description Success message
                 * @example User created successfully. Please check your email to verify your account.
                 */
                message: string;
                /** @description Created user details */
                user: components["schemas"]["RegisteredUser"];
            };
            /**
             * @description Always true for successful responses
             * @example true
             */
            success: boolean;
        };
        UpdateUserRequest: {
            /**
             * @description New full name for the user
             * @example John Smith
             */
            full_name: string;
        };
        UpdateUserResponse: {
            /**
             * @description Email address
             * @example john@example.com
             */
            email: string;
            /**
             * @description Updated full name
             * @example John Smith
             */
            full_name: string;
            /**
             * @description User ID (UUID)
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            user_id: string;
            /**
             * @description Username
             * @example johndoe
             */
            username: string;
        };
        UserProfileResponse: {
            /**
             * @description Email address
             * @example john@example.com
             */
            email: string;
            /**
             * @description Full name
             * @example John Doe
             */
            full_name: string;
            /**
             * @description User ID (UUID)
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            user_id: string;
            /**
             * @description Username
             * @example johndoe
             */
            username: string;
        };
        VerifyEmailResponse: {
            /**
             * @description Success message
             * @example Email verified successfully
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    verify_user_email_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Email verification token from the registration email */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "message": "Email verified successfully"
                     *       },
                     *       "success": true
                     *     }
                     */
                    "application/json": {
                        data: {
                            /**
                             * @description Success message
                             * @example Email verified successfully
                             */
                            message: string;
                        };
                        /**
                         * @description Always true for successful responses
                         * @example true
                         */
                        success: boolean;
                    };
                };
            };
            /** @description Invalid or expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_NOT_FOUND",
                     *         "message": "User not found"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INTERNAL_ERROR",
                     *         "message": "An unexpected error occurred"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_user_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *         "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *         "user": {
                     *           "email": "john@example.com",
                     *           "id": "123e4567-e89b-12d3-a456-426614174000",
                     *           "isVerified": true,
                     *           "username": "johndoe"
                     *         }
                     *       },
                     *       "success": true
                     *     }
                     */
                    "application/json": {
                        data: {
                            /**
                             * @description JWT access token (short-lived)
                             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                             */
                            access_token: string;
                            /**
                             * @description JWT refresh token (long-lived)
                             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                             */
                            refresh_token: string;
                            /** @description Authenticated user information */
                            user: components["schemas"]["LoginUserInfo"];
                        };
                        /**
                         * @description Always true for successful responses
                         * @example true
                         */
                        success: boolean;
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_CREDENTIALS",
                     *         "message": "Invalid email or password"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Account has been deleted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_DELETED",
                     *         "message": "This account has been deleted"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INTERNAL_ERROR",
                     *         "message": "An unexpected error occurred"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_user_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequestDto"];
            };
        };
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "message": "Logged out successfully"
                     *       },
                     *       "success": true
                     *     }
                     */
                    "application/json": {
                        data: {
                            /**
                             * @description Success message
                             * @example Logged out successfully
                             */
                            message: string;
                        };
                        /**
                         * @description Always true for successful responses
                         * @example true
                         */
                        success: boolean;
                    };
                };
            };
        };
    };
    refresh_token_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequestDto"];
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *         "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                     *       },
                     *       "success": true
                     *     }
                     */
                    "application/json": {
                        data: {
                            /**
                             * @description New JWT access token
                             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                             */
                            access_token: string;
                            /**
                             * @description New JWT refresh token
                             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                             */
                            refresh_token: string;
                        };
                        /**
                         * @description Always true for successful responses
                         * @example true
                         */
                        success: boolean;
                    };
                };
            };
            /** @description Bad request - invalid token type or token not yet valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized - token expired or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INTERNAL_ERROR",
                     *         "message": "An unexpected error occurred"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register_user_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "message": "User created successfully. Please check your email to verify your account.",
                     *         "user": {
                     *           "email": "john@example.com",
                     *           "fullName": "John Doe",
                     *           "id": "123e4567-e89b-12d3-a456-426614174000",
                     *           "username": "johndoe"
                     *         }
                     *       },
                     *       "success": true
                     *     }
                     */
                    "application/json": {
                        data: {
                            /**
                             * @description Success message
                             * @example User created successfully. Please check your email to verify your account.
                             */
                            message: string;
                            /** @description Created user details */
                            user: components["schemas"]["RegisteredUser"];
                        };
                        /**
                         * @description Always true for successful responses
                         * @example true
                         */
                        success: boolean;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_ALREADY_EXISTS",
                     *         "message": "User already exists"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INTERNAL_ERROR",
                     *         "message": "An unexpected error occurred"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_cvs_handler: {
        parameters: {
            query?: {
                /**
                 * @description Search term to filter CVs
                 * @example engineer
                 */
                search?: string;
                /** @description Sort order for results */
                sort?: components["schemas"]["CVSort"];
                /**
                 * @description Page number (starts at 1, defaults to 1)
                 * @example 1
                 */
                page?: number;
                /**
                 * @description Items per page (defaults to 10)
                 * @example 10
                 */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CVs retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "items": [
                     *           {
                     *             "bio": "Passionate software engineer...",
                     *             "contactInfo": [],
                     *             "coreSkills": [],
                     *             "displayName": "John Doe",
                     *             "educations": [],
                     *             "experiences": [],
                     *             "highlightedProjects": [],
                     *             "id": "123e4567-e89b-12d3-a456-426614174000",
                     *             "photoUrl": "https://example.com/photos/profile.jpg",
                     *             "role": "Senior Software Engineer",
                     *             "userId": "987e6543-e21b-12d3-a456-426614174000"
                     *           }
                     *         ],
                     *         "page": 1,
                     *         "perPage": 10,
                     *         "total": 5
                     *       },
                     *       "success": true
                     *     }
                     */
                    "application/json": {
                        data: {
                            /** @description List of items in the current page */
                            items: {
                                /**
                                 * @description Biography
                                 * @example Passionate software engineer...
                                 */
                                bio: string;
                                /** @description Contact information */
                                contact_info: components["schemas"]["ContactDetail"][];
                                /** @description Core skills */
                                core_skills: components["schemas"]["CoreSkill"][];
                                /**
                                 * @description Display name
                                 * @example John Doe
                                 */
                                display_name: string;
                                /** @description Educational background */
                                educations: components["schemas"]["Education"][];
                                /** @description Work experiences */
                                experiences: components["schemas"]["Experience"][];
                                /** @description Highlighted projects */
                                highlighted_projects: components["schemas"]["HighlightedProject"][];
                                /**
                                 * Format: uuid
                                 * @description CV unique identifier
                                 * @example 123e4567-e89b-12d3-a456-426614174000
                                 */
                                id: string;
                                /**
                                 * @description Profile photo URL
                                 * @example https://example.com/photos/profile.jpg
                                 */
                                photo_url: string;
                                /**
                                 * @description Professional role
                                 * @example Senior Software Engineer
                                 */
                                role: string;
                                /**
                                 * Format: uuid
                                 * @description Owner user ID
                                 * @example 987e6543-e21b-12d3-a456-426614174000
                                 */
                                user_id: string;
                            }[];
                            /**
                             * Format: int32
                             * @description Current page number
                             * @example 1
                             */
                            page: number;
                            /**
                             * Format: int32
                             * @description Number of items per page
                             * @example 10
                             */
                            per_page: number;
                            /**
                             * Format: int64
                             * @description Total number of items across all pages
                             * @example 42
                             */
                            total: number;
                        };
                        /**
                         * @description Always true for successful responses
                         * @example true
                         */
                        success: boolean;
                    };
                };
            };
            /** @description Not authenticated or not verified */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_cv_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCVRequest"];
            };
        };
        responses: {
            /** @description CV created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "bio": "Passionate software engineer...",
                     *         "contactInfo": [],
                     *         "coreSkills": [
                     *           {
                     *             "description": "Expert in Rust, Python, and Node.js",
                     *             "title": "Backend Development"
                     *           }
                     *         ],
                     *         "displayName": "John Doe",
                     *         "educations": [],
                     *         "experiences": [],
                     *         "highlightedProjects": [],
                     *         "id": "123e4567-e89b-12d3-a456-426614174000",
                     *         "photoUrl": "https://example.com/photos/profile.jpg",
                     *         "role": "Senior Software Engineer",
                     *         "userId": "987e6543-e21b-12d3-a456-426614174000"
                     *       },
                     *       "success": true
                     *     }
                     */
                    "application/json": {
                        data: {
                            /**
                             * @description Biography
                             * @example Passionate software engineer...
                             */
                            bio: string;
                            /** @description Contact information */
                            contact_info: components["schemas"]["ContactDetail"][];
                            /** @description Core skills */
                            core_skills: components["schemas"]["CoreSkill"][];
                            /**
                             * @description Display name
                             * @example John Doe
                             */
                            display_name: string;
                            /** @description Educational background */
                            educations: components["schemas"]["Education"][];
                            /** @description Work experiences */
                            experiences: components["schemas"]["Experience"][];
                            /** @description Highlighted projects */
                            highlighted_projects: components["schemas"]["HighlightedProject"][];
                            /**
                             * Format: uuid
                             * @description CV unique identifier
                             * @example 123e4567-e89b-12d3-a456-426614174000
                             */
                            id: string;
                            /**
                             * @description Profile photo URL
                             * @example https://example.com/photos/profile.jpg
                             */
                            photo_url: string;
                            /**
                             * @description Professional role
                             * @example Senior Software Engineer
                             */
                            role: string;
                            /**
                             * Format: uuid
                             * @description Owner user ID
                             * @example 987e6543-e21b-12d3-a456-426614174000
                             */
                            user_id: string;
                        };
                        /**
                         * @description Always true for successful responses
                         * @example true
                         */
                        success: boolean;
                    };
                };
            };
            /** @description Not authenticated or not verified */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_user_profile_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "email": "john@example.com",
                     *         "fullName": "John Doe",
                     *         "userId": "123e4567-e89b-12d3-a456-426614174000",
                     *         "username": "johndoe"
                     *       },
                     *       "success": true
                     *     }
                     */
                    "application/json": {
                        data: {
                            /**
                             * @description Email address
                             * @example john@example.com
                             */
                            email: string;
                            /**
                             * @description Full name
                             * @example John Doe
                             */
                            full_name: string;
                            /**
                             * @description User ID (UUID)
                             * @example 123e4567-e89b-12d3-a456-426614174000
                             */
                            user_id: string;
                            /**
                             * @description Username
                             * @example johndoe
                             */
                            username: string;
                        };
                        /**
                         * @description Always true for successful responses
                         * @example true
                         */
                        success: boolean;
                    };
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UNAUTHORIZED",
                     *         "message": "Authentication required"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_NOT_FOUND",
                     *         "message": "User not found: User does not exist"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INTERNAL_ERROR",
                     *         "message": "An unexpected error occurred"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_user_profile_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "email": "john@example.com",
                     *         "fullName": "John Smith",
                     *         "userId": "123e4567-e89b-12d3-a456-426614174000",
                     *         "username": "johndoe"
                     *       },
                     *       "success": true
                     *     }
                     */
                    "application/json": {
                        data: {
                            /**
                             * @description Email address
                             * @example john@example.com
                             */
                            email: string;
                            /**
                             * @description Updated full name
                             * @example John Smith
                             */
                            full_name: string;
                            /**
                             * @description User ID (UUID)
                             * @example 123e4567-e89b-12d3-a456-426614174000
                             */
                            user_id: string;
                            /**
                             * @description Username
                             * @example johndoe
                             */
                            username: string;
                        };
                        /**
                         * @description Always true for successful responses
                         * @example true
                         */
                        success: boolean;
                    };
                };
            };
            /** @description Invalid full name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_FULL_NAME",
                     *         "message": "Full name must be between 2 and 100 characters"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UNAUTHORIZED",
                     *         "message": "Authentication required"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INTERNAL_ERROR",
                     *         "message": "An unexpected error occurred"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    soft_delete_user_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User account deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated or not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_UNAUTHORIZED",
                     *         "message": "You are not authorized to delete this account"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_NOT_FOUND",
                     *         "message": "User not found"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INTERNAL_ERROR",
                     *         "message": "An unexpected error occurred"
                     *       },
                     *       "success": false
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
